### ISSUE TITLE
Why does the Flathub website tag akregator as "proprietary?"

### ISSUE THREAD

**Issue by 1bcb** [flathub/org.kde.akregator#112]
The flathub [store page says](https://flathub.org/apps/org.kde.akregator)

> This software is not developed in the open, so only its developers know how it works. It may be insecure in ways that are hard to detect, and it may change without oversight.

Is this a mistake?

**Comment by tsdgeos** [comment]
Of course it is a mistake.

**Comment by travier** [comment]
This should be fixed by https://invent.kde.org/pim/akregator/-/merge_requests/40
